apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-deployment
  labels:
    app: wishlist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wishlist
  template:
    metadata:
      labels:
        app: wishlist
    spec:
      containers:
        - name: wishlist-container
          image: iampraveeen/wishlist:latest  # Replace with your actual image
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql"               # Example: external DB host
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "password"

---

apiVersion: v1
kind: Service
metadata:
  name: wishlist-service
spec:
  type: NodePort
  selector:
    app: wishlist
  ports:
    - port: 80             # External service port
      targetPort: 8080     # Container port
      nodePort: 30045      # Must be within 30000-32767

